modLoader="javafml" #mandatory
loaderVersion="[28.1]" #mandatory. 26 for 1.14.2, 27 for 1.14.3
[[mods]] #mandatory
modId="testmod" #mandatory
version="1.0" #mandatory
displayName="Manin Stenr" #mandatory
description='''
Lorem ipsum dolorem.
'''